---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant
    db_user: vagrant
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: get the local user name
      sudo: false
      local_action:
        shell /usr/bin/whoami
      register: whoami_result
    - name: store the local user name
      set_fact:
        username_on_the_host: "{{ whoami_result.stdout }}"
  roles:
    - common
    - common-python
    - redis
    - postgres
    - lk-django
    - lk-review-ingester
    - lk-go-devproxy
    - lk-google-app-engine
    - lk-skit

  post_tasks:
    - name: start launchkit
      service: name=launchkit state=started
      ignore_errors: yes
